name: Test

on:
  - pull_request
  - push

env:
  BUNDLE_WITHOUT: release

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Rubocop
    steps:
      - uses: actions/checkout@v2
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Rubocop
        run: |
          bundle exec rubocop

  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: "2.7"
          - ruby: "3.0"
          - ruby: "3.1"
            coverage: "yes"
    env:
      COVERAGE: ${{ matrix.coverage }}
    name: Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake spec
      - name: Verify gem builds
        run: gem build *.gemspec
